# Generated by Django 5.1 on 2024-08-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='heading',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
